# Generated by Django 5.2.17 on 2026-09-21 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveuniverse", "0012_alter_evebloodline_eve_ship_type"),
        ("markettracker", "0018_alter_trackeditem_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackedItemGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("desired_quantity", models.PositiveIntegerField(default=0)),
                ("last_status", models.CharField(default="OK", max_length=10)),
                (
                    "items",
                    models.ManyToManyField(
                        related_name="market_tracking_groups", to="eveuniverse.evetype"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_groups",
                        to="markettracker.trackedlocation",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "default_permissions": (),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("location", "name"), name="mt_item_group_location_name"
                    )
                ],
            },
        ),
    ]
